export const predefinedCategories: string[] = [
  "Biotechnology & Synthetic Biology",
  "Genetics & Genomics",
  "Healthcare & Medicine",
  "Longevity & Aging",
  "Biosecurity & Biodefense",
  "Neuroscience",
  "Materials Science & Engineering",
  "Quantum Computing",
  "Robotics & AI",
  "Nanotechnology",
  "Space & Astronomy",
  "Neurotechnology",
  "Climate & Atmospheric Science",
  "Renewable Energy",
  "Ocean & Marine Science",
  "Conservation Biology",
  "Agriculture & Food Systems",
  "Environmental Health",
  "Artificial Intelligence (AI)",
  "Machine Learning (ML)",
  "Bioinformatics",
  "Chemoinformatics",
  "High-Performance Computing",
  "Data Analytics",
  "Natural Language Processing",
  "Biochemistry",
  "Chemistry",
  "Physics",
  "Biology",
  "Mathematics",
  "Photonics",
  "Computer Vision",
  "Other",
]; 